services:
  manager:
    image: golang:1.22.5-bookworm
    ports:
      - 8010:8010
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/server.go

  postgres:
    image: postgres:16.3-bookworm
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  vite-app:
    image: node:22-bookworm-slim
    volumes:
      - ./web:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'

networks:
  elpis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
