services:
  proxy:
    image: golang:1.22.5-bookworm
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/server.go
    networks:
      elpis_network:
        ipv4_address: 172.21.0.6

networks:
  elpis_network:
    external: true
    name: elpis_network
